package com.econome.participantes.enums;

public enum TipoParticipante {
    CLIENTE, FORNECEDOR, TRANSPORTADORA, COLABORADOR, ASSISTENCIA_TECNICA, ADMINISTRADORA, CONSULTORIA,
    CONTABILIDADE, OUTROS
}
